# Generated by Django 5.2.1 on 2025-09-01 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereço', models.CharField(blank=True, max_length=250, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('tipo_obra', models.CharField(choices=[('PREDIO', 'Prédio'), ('CONDOMINIO', 'Condomínio de Casas'), ('LOTEAMENTO', 'Loteamento')], default='PREDIO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DespesasMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('ano', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engenharia.obras')),
            ],
        ),
        migrations.CreateModel(
            name='DespesasItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('documento', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('despesas_mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='engenharia.despesasmes')),
            ],
        ),
        migrations.CreateModel(
            name='MesPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('ano', models.IntegerField()),
                ('obra', models.ForeignKey(blank=True, null=-1, on_delete=django.db.models.deletion.CASCADE, related_name='ponto_mes', to='engenharia.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('final', models.DateField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engenharia.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=100)),
                ('situacao', models.CharField(choices=[('ASSINADO', 'Assinado'), ('FREE', 'Freelancer')], default='ASSINADO', max_length=20)),
                ('obra', models.ForeignKey(blank=True, null=-1, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='engenharia.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Andar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andares', to='engenharia.obras')),
            ],
            options={
                'unique_together': {('obra', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ServicoCronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('nivel', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
                ('titulo', models.CharField(max_length=150)),
                ('inicio', models.DateField()),
                ('dias', models.IntegerField(blank=True, null=True)),
                ('fim', models.DateField(blank=True)),
                ('progresso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('codigo', models.CharField(blank=True, editable=False, max_length=50)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='engenharia.cronograma')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subservicos', to='engenharia.servicocronograma')),
                ('predecessores', models.ManyToManyField(blank=True, related_name='sucessores', to='engenharia.servicocronograma')),
            ],
        ),
        migrations.AddField(
            model_name='obras',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='obras', to='engenharia.servicos'),
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ou_numero', models.CharField(max_length=50)),
                ('andar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='engenharia.andar')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='engenharia.obras')),
            ],
            options={
                'unique_together': {('obra', 'andar', 'nome_ou_numero')},
            },
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('entrada_manha', models.TimeField()),
                ('entrada_tarde', models.TimeField()),
                ('saida_manha', models.TimeField(blank=True, null=True)),
                ('saida_tarde', models.TimeField(blank=True, null=True)),
                ('horas_trabalhadas', models.CharField(blank=True, max_length=150, null=True)),
                ('feriado', models.BooleanField(default=False, verbose_name='Feriado?')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='engenharia.colaborador')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('colaborador', 'data'), name='unique_ponto_colaborador_dia')],
            },
        ),
        migrations.CreateModel(
            name='ServicoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='NAO_INICIADO', max_length=20)),
                ('progresso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engenharia.servicos')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_unidade', to='engenharia.unidade')),
            ],
            options={
                'unique_together': {('unidade', 'servico')},
            },
        ),
    ]
