# Generated by Django 5.2.1 on 2025-05-09 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesasitem',
            name='despesas_mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='engenharia.despesasmes'),
        ),
    ]
