# Generated by Django 5.2.1 on 2025-05-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0002_alter_despesasitem_despesas_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesasmes',
            name='mes',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1),
        ),
    ]
