# Generated by Django 5.2.1 on 2025-05-09 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0003_alter_despesasmes_mes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesasitem',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
