# Generated by Django 5.2.1 on 2025-05-10 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0004_alter_despesasitem_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesasitem',
            name='empresa',
            field=models.CharField(max_length=150),
        ),
    ]
