# Generated by Django 5.2.1 on 2025-05-11 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0005_alter_despesasitem_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereço', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
