# Generated by Django 5.2.1 on 2025-05-11 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0006_obras'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesasmes',
            name='obra',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engenharia.obras'),
            preserve_default=False,
        ),
    ]
