# Generated by Django 5.2.1 on 2025-07-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0008_cronograma_servicocronograma'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicocronograma',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
