# Generated by Django 5.2.1 on 2025-07-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0009_servicocronograma_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicocronograma',
            name='predecessores',
            field=models.ManyToManyField(blank=True, related_name='sucessores', to='engenharia.servicocronograma'),
        ),
    ]
