# Generated by Django 5.2.1 on 2025-07-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0010_servicocronograma_predecessores'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicocronograma',
            name='dias',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
