# Generated by Django 5.2.1 on 2025-07-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0012_servicocronograma_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicocronograma',
            name='dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicocronograma',
            name='fim',
            field=models.DateField(blank=True),
        ),
    ]
