# Generated by Django 5.2.1 on 2025-07-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0013_alter_servicocronograma_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicocronograma',
            name='uid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
