# Generated by Django 5.2.1 on 2025-07-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0014_alter_servicocronograma_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='final',
            field=models.DateField(blank=True, null=True),
        ),
    ]
