# Generated by Django 5.2.1 on 2025-08-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0015_cronograma_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=100)),
                ('situacao', models.CharField(choices=[('ASSINADO', 'Assinado'), ('FREE', 'Freelancer')], default='ASSINADO', max_length=20)),
                ('obra', models.ForeignKey(blank=True, null=-1, on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='engenharia.obras')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('entrada_manha', models.TimeField()),
                ('entrada_tarde', models.TimeField()),
                ('saida_manha', models.TimeField(blank=True, null=True)),
                ('saida_tarde', models.TimeField(blank=True, null=True)),
                ('horas_trabalhadas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='engenharia.colaborador')),
            ],
        ),
    ]
