# Generated by Django 5.2.1 on 2025-08-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0016_colaborador_ponto'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='ponto',
            constraint=models.UniqueConstraint(fields=('colaborador', 'data'), name='unique_ponto_colaborador_dia'),
        ),
        migrations.AddField(
            model_name='mesponto',
            name='obra',
            field=models.ForeignKey(blank=True, null=-1, on_delete=django.db.models.deletion.CASCADE, related_name='ponto_mes', to='engenharia.obras'),
        ),
    ]
