# Generated by Django 5.2.1 on 2025-08-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0017_mesponto_ponto_unique_ponto_colaborador_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='feriado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='horas_trabalhadas',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
