# Generated by Django 5.2.1 on 2025-08-30 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engenharia', '0018_ponto_feriado_alter_ponto_horas_trabalhadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='obras',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='obras',
            name='tipo_obra',
            field=models.CharField(choices=[('PREDIO', 'Prédio'), ('CONDOMINIO', 'Condomínio de Casas'), ('LOTEAMENTO', 'Loteamento')], default='PREDIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='ponto',
            name='feriado',
            field=models.BooleanField(default=False, verbose_name='Feriado?'),
        ),
        migrations.CreateModel(
            name='Andar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_andar', models.IntegerField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andares', to='engenharia.obras')),
            ],
            options={
                'unique_together': {('obra', 'numero_andar')},
            },
        ),
        migrations.AddField(
            model_name='obras',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='obras', to='engenharia.servicos'),
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ou_numero', models.CharField(max_length=50)),
                ('andar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='engenharia.andar')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='engenharia.obras')),
            ],
            options={
                'unique_together': {('obra', 'andar', 'nome_ou_numero')},
            },
        ),
        migrations.CreateModel(
            name='ServicoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído')], default='NAO_INICIADO', max_length=20)),
                ('progresso', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engenharia.servicos')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_unidade', to='engenharia.unidade')),
            ],
            options={
                'unique_together': {('unidade', 'servico')},
            },
        ),
    ]
